In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
!pip install ydata-profiling

Requirement already satisfied: ydata-profiling in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (4.16.1)
Requirement already satisfied: scipy<1.16,>=1.4.1 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (1.15.2)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (2.2.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic>=2 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (2.11.3)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.2,>=1.16.0 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (2.1.3)
Requirement already satisfied: htmlmin==0.1.12 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (0.12.4)
Requirement already satisfied: requests<3,>=2.24.0 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.48.2 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (0.14.4)
Requirement already satisfied: typeguard<5,>=3 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (4.4.2)
Requirement already satisfied: imagehash==4.3.1 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (1.9.4)
Requirement already satisfied: dacite>=1.8 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<=0.61,>=0.56.0 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from ydata-profiling) (0.61.0)
Requirement already satisfied: PyWavelets in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from imagehash==4.3.1->ydata-profiling) (1.8.0)
Requirement already satisfied: pillow in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from imagehash==4.3.1->ydata-profiling) (11.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (2.1.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.1.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from pydantic>=2->ydata-profiling) (2.33.1)
Requirement already satisfied: typing-extensions>=4.12.2 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from pydantic>=2->ydata-profiling) (4.13.1)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from pydantic>=2->ydata-profiling) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2025.1.31)
Requirement already satisfied: patsy>=0.5.6 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: colorama in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from tqdm<5,>=4.48.2->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.4.2)
Requirement already satisfied: puremagic in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (1.28)
Requirement already satisfied: six>=1.5 in c:\users\hp\onedrive\desktop\ml learnings\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

In [5]:
from ydata_profiling import ProfileReport
prof = ProfileReport(df)

In [6]:
prof.to_file(output_file = "output.html")

100%|██████████| 12/12 [00:00<00:00, 51.51it/s]0<00:00, 21.80it/s, Describe variable: Embarked]
Summarize dataset: 100%|██████████| 47/47 [00:03<00:00, 12.95it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.27s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.97s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 50.74it/s]

In [10]:
cropdata = pd.read_csv('crop_price_dataset.csv')
cropdata.head()

,month,commodity_name,avg_modal_price,avg_min_price,avg_max_price,state_name,district_name,calculationType,change
0,2025-03-01,Maize,2341.58,2191.23,2402.98,India,All,Monthly,-14.43
1,2025-02-01,Maize,2356.01,2202.35,2414.46,India,All,Monthly,-26.19
2,2025-01-01,Maize,2382.20,2221.31,2448.22,India,All,Monthly,53.42
3,2024-12-01,Maize,2328.78,2164.86,2411.66,India,All,Monthly,55.32
4,2024-11-01,Maize,2273.46,2077.63,2377.78,India,All,Monthly,35.48

In [11]:
crop_prof = ProfileReport(cropdata)
crop_prof.to_file(output_file = "cropAnalysis.html")

100%|██████████| 9/9 [00:00<?, ?it/s]/14 [00:00<00:00, 28.48it/s, Describe variable: change]
Summarize dataset: 100%|██████████| 34/34 [00:02<00:00, 13.44it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.71s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.55it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 125.08it/s]